version: '3'

services:
  block_chain_elixir:
    container_name: block_chain_elixir
    build: .
    command: dockerize -wait tcp://db_block_chain:5432 -timeout 40s ./.devcontainer/entrypoint.sh
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: blockChain
      PGPORT: 5432
      PGHOST: db_block_chain
    ports:
      - 4000:4000
    networks:
      - app-network
    volumes:
      - ../:/blockChainElixir:cached
      - ../:/home/elixir/app

  db_block_chain:
    build: ./postgres
    container_name: db_block_chain
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blockChain
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - .docker/pgdata:/var/lib/postgresql/data

  db_block_chain_test:
    build: ./postgres
    container_name: db_block_chain_test
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blockChain_test
    networks:
      - app-network
    volumes:
      - .docker/pgdatatest:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge
